config/routes.rb
Rails.application.routes.draw do

  resources :companies do
    resources :jobs
    resources :contacts, only: [:create]
  end

  resources :jobs, except: [:index] do
    resources :comments, only: [:create]
  end

  get '/jobs' => 'jobs#all_jobs'

  resources :categories

  get '/dashboard' => 'dashboard#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :title, presence: true
  validates :title, uniqueness: true

  has_many :jobs
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :job_id, presence: true

  belongs_to :job
end

app/models/company.rb
class Company < ActiveRecord::Base
  validates :name, :city, presence: true
  validates :name, uniqueness: true

  has_many :jobs, dependent: :destroy
  has_many :contacts, dependent: :destroy
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :full_name, :position, :email, :company_id, presence: true
  belongs_to :company
end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :title, :level_of_interest, :category_id, presence: true
  belongs_to :company
  belongs_to :category
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "You created #{@category.title}"
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to category_path(@category)
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.delete

    flash[:success] = "#{@category.title} was successfully deleted!"
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @job = Job.find(params[:job_id])
    @company = @job.company
    @comment = @job.comments.new(comment_params)
    if @comment.update(comment_params)
      redirect_to company_job_path(@company, @job)
    else
      render company_job_path(@company, @job)
    end
  end


  private

  def comment_params
    params.require(:comment).permit(:content, :job_id)
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
    if params[:sort] == "location"
      @companies = @companies.sort_by do |company|
        company.city
      end
    end
    if !params[:location].nil?
      @companies = @companies.where(city: params[:location])
    end
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      flash[:success] = "#{@company.name} added!"
      redirect_to company_path(@company)
    else
      render :new
    end
  end

  def show
    company = Company.find(params[:id])
    redirect_to company_jobs_path(company)
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    @company.update(company_params)
    if @company.save
      flash[:success] = "#{@company.name} updated!"
      redirect_to company_path(@company)
    else
      render :edit
    end
  end

  def destroy
    company = Company.find(params[:id])
    company.destroy

    flash[:success] = "#{company.name} was successfully deleted!"
    redirect_to companies_path
  end


  private

  def company_params
    params.require(:company).permit(:name, :city)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def create
    @company = Company.find(params[:company_id])
    @contact = @company.contacts.new(contact_params)
    if @contact.update(contact_params)
      redirect_to company_jobs_path(@company)
    else
      render company_jobs_path(@company)
    end

  end
  

  private

  def contact_params
    params.require(:contact).permit(:full_name, :position, :email, :company_id)
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @cities = Company.all.group(:city).count
    @interest = Job.all.group(:level_of_interest).count
    @average_interest = Job.group(:company_id).average(:level_of_interest).sort_by {|k,v| v}.reverse[0..2]
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @company = Company.find(params[:company_id])
    @jobs = @company.jobs
    @contact = Contact.new
  end

  def all_jobs
    @jobs = Job.all
    if params[:sort] == "interest"
      @jobs = @jobs.sort_by do |job|
        job.level_of_interest
      end
    end
  end

  def new
    @company = Company.find(params[:company_id])
    @job = Job.new()
  end


  def create
    @company = Company.find(params[:company_id])
    @job = @company.jobs.new(job_params)
    if @job.save
      flash[:success] = "You created #{@job.title} at #{@company.name}"
      redirect_to company_job_path(@company, @job)
    else
      render :new
    end
  end

  def show
    @job = Job.find(params[:id])
    @company = @job.company
    @comment = Comment.new
  end

  def edit
    @job = Job.find(params[:id])
    @company = @job.company
  end

  def update
    @job = Job.find(params[:id])
    @company = @job.company
    if @job.update(job_params)
      redirect_to company_job_path(@company, @job)
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @company = @job.company
    @job.destroy
    flash[:success] = "#{@job.title} was successfully deleted!"
    redirect_to company_jobs_path
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :level_of_interest, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
<h2> Edit Category </h2>

<%= render partial: "form" %>

</div>

app/views/categories/index.html.erb
<div class="container">
<h2> All Categories </h2>

<ul>
  <% @categories.each do |category| %>
<li>  <%= category.title %>
      <%= link_to "Edit", edit_category_path(category) %>
      <%= link_to "Delete", category_path(category), method: "delete"%>
</li>
  <% end %>
</ul>
<div>
  <%= link_to "Create New", new_category_path %>
</div>
</div>

app/views/categories/new.html.erb
<div class="container">
<h2>Create a new category</h2>

<%= render partial: "form" %>
</div>

app/views/categories/show.html.erb
<div class="container">
<h2> Category: <%= @category.title %> </h2>

<h3> Jobs in this category: </h3>

<ul>
  <% @category.jobs.each do |job| %>
  <li><%= job.title %></li>
  <% end %>
</ul>
</div>

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.submit %>
<% end %>

app/views/companies/edit.html.erb
<div class="container">
<h2>Edit <%= @company.name %>:</h2>

<%= render partial: "form" %>
</div>

app/views/companies/index.html.erb
<div class="container">
<h3>All Companies</h3>
<div>
  <%= link_to "View by location", "/companies?sort=location" %>
</div>
<% @companies.each do |company| %>
  <ul class=company_<%= company.id %>>
    <%= link_to company.name, company_path(company) %> - <%= company.city %><br>
    <%= link_to edit_company_path(company) do %>
    <button type="button" class="btn btn-success" aria-haspopup="true" aria-expanded="false">
      <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
    </button>
    <% end %>
    <%= link_to company_path(company), method: "delete" do %>
    <button type="button" class="btn btn-danger" aria-haspopup="true" aria-expanded="false"> Delete
    </button>
    <% end %>
  </ul>
<% end %>

<!-- Single button -->
<div class="btn-group">
  <a href="/companies/new"><button type="button" class="btn btn-success" aria-haspopup="true" aria-expanded="false">
    Create New
  </button></a>
</div>

</div>

app/views/companies/new.html.erb
<div class="container">
<h2>Create a new company: </h2>

<%= render partial: "form" %>
</div>

app/views/companies/show.html.erb
<div class="container">
<h2>All Jobs for <strong><%= @company.name %></strong></h2>

<% @company.jobs.each do |job| %>
  <ul><%= job.title %></ul>
<% end %>
</div>

app/views/dashboard/index.html.erb
<div class="container">
<h2>Dashboard</h2>

<div class="row">
  <div class="col-md-4">
    <h4>Jobs by level of interest</h4>
    <% @interest.each do |interest, count| %>
      <li><%= interest %>
      <span class="badge"><%= count %></span></li>
    <% end %>
  </div>
  <div class="col-md-4">
    <h4>Top 3 companies by average interest level</h4>
    <% @average_interest.each do |company, interest| %>
    <li><%= Company.find(company).name %>
      <span class="badge"><%= interest %></span></li>
      <% end %>
  </div>
  <div class="col-md-4">
    <h4>Jobs by location</h4>
    <% @cities.each do |city, count| %>
    <li><%= link_to city, "/companies?location=#{city}" %>
    <span class="badge"><%= count %></span></li>
    <% end %>
  </div>
</div>

</div>

app/views/jobs/_form.html.erb
<%= form_for([@company, @job]) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :level_of_interest %>
  <%= f.number_field :level_of_interest %>

  <%= f.collection_select(:category_id, Category.all, :id, :title, { prompt: "Select Category" }) %>

  <%= f.submit %>
<% end %>

<%= link_to "Create new category", new_category_path %>

app/views/jobs/all_jobs.html.erb
<% @jobs.each do |job| %>
<ul>
  <li>Level of Interest:   <%= job.level_of_interest %> for
    <%= link_to job.title, company_job_path(job.company, job) %> at <%= job.company.name %>
    <br>
    <%= link_to edit_company_job_path(job.company, job) do %>
    <button type="button" class="btn btn-success" aria-haspopup="true" aria-expanded="false">
      <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
    </button>
    <% end %>
    <%= link_to company_job_path(job.company, job), method: "delete" do %>
    <button type="button" class="btn btn-danger" aria-haspopup="true" aria-expanded="false">
      <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
    </button>
    <% end %>
  </li>
</ul>
<% end %>

app/views/jobs/edit.html.erb
<div class="container">
<h2>Edit Job at <%= @company.name %></h2>

<%= render partial: "form" %>
</div>

app/views/jobs/index.html.erb
<div class="container">
<h2>All Jobs for <%= @company.name %></h2>

<% @jobs.each do |job| %>
  <ul>
  <%= link_to job.title, company_job_path(@company, job) %> at <%= job.company.name %>
  <%= link_to "Edit", edit_company_job_path(@company, job) %>
  <%= link_to "Delete", company_job_path(@company, job), method: "delete" %>
  </ul>
<% end %>
<div>
  <%= link_to new_company_job_path do %>
  <button type="button" class="btn btn-success" aria-haspopup="true" aria-expanded="false">
    Create New
  </button>
  <% end %>
</div>

<div>
  <h3> Add a contact person for <%= @company.name %>:</h3>

  <%= form_for ([@company, @contact]) do |f| %>
    <%= f.label :Name %>
    <%= f.text_field :full_name %>

    <%= f.label :Position %>
    <%= f.text_field :position %>

    <%= f.label :Email %>
    <%= f.text_field :email %>

    <%= f.submit %>
  <% end %>

</div>

<div>
  <h4>Contacts at <%= @company.name %>: </h4>
  <% @company.contacts.each do |contact| %>
  <ul>
    <%= contact.full_name %> -
    <%= contact.position %> -
    <%= contact.email %>
  </ul>
  <% end %>

</div>
</div>

app/views/jobs/new.html.erb
<div class="container">
<h2>Create a new job at <%= @company.name %> here!</h2>

<%= render partial: "form" %>
</div>

app/views/jobs/show.html.erb
<div class="container">
  Title: <%= @job.title %>
  <br>

  Description: <%= @job.description %>
  <br>

  Level of Interest: <%= @job.level_of_interest %>
  <br>

  Category: <%= link_to @job.category.title, category_path(@job.category) %>
  <br>

  Company: <%= link_to @job.company.name, company_path(@job.company) %>

  <br>
  <br>
  <div>
    <h3>Leave a comment:</h3>
    <%= form_for ([@job, @comment]) do |f| %>
    <%= f.label :comment %>
    <%= f.text_field :content %>

    <%= f.submit %>
    <% end %>
  </div>
  <div class="comment">
    <h4>Comments about this job: </h4>
    <% @job.comments.reverse.each do |comment| %>
    <ul>
      <%= comment.content %>
    </ul>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">

</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/dashboard">Job Tracker</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/companies">Companies</a></li>
        <li><a href="/jobs">Jobs</a></li>
        <li><a href="/categories">Categories</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: name %>
  <% end %>
<%= yield %>

</body>
</html>